FROM node as builder
RUN mkdir /react_server
WORKDIR /react_server
ADD . /react_server/

RUN npm install yarn
RUN yarn install
RUN yarn build

# Copy built app into nginx container
FROM nginx
COPY --from=builder /react_server/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
